//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmDetay
    {
        public int FilmId { get; set; }
        public int KategoriId { get; set; }
        public int YapimSirketiId { get; set; }
    
        public virtual Filmler Filmler { get; set; }
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual YapimSirketleri YapimSirketleri { get; set; }
    }
}
