//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KisilerFilmler
    {
        public int KisiFilmlerId { get; set; }
        public int FilmId { get; set; }
        public int KisiId { get; set; }
        public int GorevId { get; set; }
        public bool Durum { get; set; }
    
        public virtual Filmler Filmler { get; set; }
        public virtual Gorevler Gorevler { get; set; }
        public virtual Kisiler Kisiler { get; set; }
    }
}
