//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doktorlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doktorlar()
        {
            this.IdariPersonellerDoktorlar = new HashSet<IdariPersonellerDoktorlar>();
            this.Muayeneler = new HashSet<Muayeneler>();
        }
    
        public int DoktorId { get; set; }
        public int BolumId { get; set; }
        public string DoktorAdi { get; set; }
        public string DoktorSoyadi { get; set; }
        public System.DateTime DoktorDogumTarihi { get; set; }
        public string DoktorAdresi { get; set; }
        public string DoktorTel { get; set; }
        public bool Durum { get; set; }
    
        public virtual Bolumler Bolumler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdariPersonellerDoktorlar> IdariPersonellerDoktorlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Muayeneler> Muayeneler { get; set; }
    }
}
