//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hastalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hastalar()
        {
            this.Muayeneler = new HashSet<Muayeneler>();
        }
    
        public int HastaId { get; set; }
        public string HastaTC { get; set; }
        public string HastaAdi { get; set; }
        public string HastaSoyadi { get; set; }
        public System.DateTime HastaDogumTarihi { get; set; }
        public string HastaAdresi { get; set; }
        public string HastaTel { get; set; }
        public bool Durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Muayeneler> Muayeneler { get; set; }
    }
}
