//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hemsireler
    {
        public int HemsireId { get; set; }
        public int BolumId { get; set; }
        public string HemsireAdi { get; set; }
        public string HemsireSoyadi { get; set; }
        public System.DateTime HemsireDogumTarihi { get; set; }
        public string HemsireAdresi { get; set; }
        public string HemsireTel { get; set; }
        public bool Durum { get; set; }
    
        public virtual Bolumler Bolumler { get; set; }
    }
}
