//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdariPersonel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IdariPersonel()
        {
            this.IdariPersonellerDoktorlar = new HashSet<IdariPersonellerDoktorlar>();
        }
    
        public int IdariPersonelId { get; set; }
        public string IdariPersonelAdi { get; set; }
        public string IdariPersonelSoyadi { get; set; }
        public System.DateTime IdariPersonelDogumTarihi { get; set; }
        public string IdariPersonelAdresi { get; set; }
        public string IdariPersonelTel { get; set; }
        public bool Durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdariPersonellerDoktorlar> IdariPersonellerDoktorlar { get; set; }
    }
}
